// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalTwitter.Models;

namespace ProyectoFinalTwitter.Migrations
{
    [DbContext(typeof(TweetCtx))]
    partial class TweetCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Like", b =>
                {
                    b.Property<int>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdTweet")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioLikeo")
                        .HasColumnType("int");

                    b.Property<int?>("LikeadorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdLike");

                    b.HasIndex("LikeadorUsuarioId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Siguiendo", b =>
                {
                    b.Property<int>("IdAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdUsuarioSiguiendo")
                        .HasColumnType("int");

                    b.Property<int?>("SeguidorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("IdAccion");

                    b.HasIndex("SeguidorUsuarioId");

                    b.ToTable("Siguiendo");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Tweet", b =>
                {
                    b.Property<int>("TweetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TweetId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Like", b =>
                {
                    b.HasOne("ProyectoFinalTwitter.Models.Usuario", "Likeador")
                        .WithMany()
                        .HasForeignKey("LikeadorUsuarioId");

                    b.Navigation("Likeador");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Siguiendo", b =>
                {
                    b.HasOne("ProyectoFinalTwitter.Models.Usuario", "Seguidor")
                        .WithMany()
                        .HasForeignKey("SeguidorUsuarioId");

                    b.Navigation("Seguidor");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Tweet", b =>
                {
                    b.HasOne("ProyectoFinalTwitter.Models.Usuario", "Autor")
                        .WithMany("Tweets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ProyectoFinalTwitter.Models.Usuario", b =>
                {
                    b.Navigation("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
